apiVersion: apps/v1
kind: Deployment
metadata:
  name: auditbenchmark-deployment
  labels:
    app: AuditBenchmarkModule
spec:
  replicas: 1
  selector:
    matchLabels:
      app: AuditBenchmarkModule  
  template:
    metadata:
      labels:
        app: AuditBenchmarkModule
    spec:
      containers:
      - name: benchmarkcontainer
        image: auditmanagementcreg.azurecr.io/benchmarkcontrepo:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: authsvcsecret
---
apiVersion: v1
kind: Service
metadata:
  name: auditbenchmarkmodule
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: auditbenchmarkmodule